#!/usr/bin/php-cli

<?php
// Variables
$dbip = "";
$dbport = "";
$dbusername = "";
$dbpassword = "";

// ----------------------------------------

// Required to fix print
echo '<br />'; 

// Setup opts array
$opts = array();
$argv0 = array_shift($argv);
while(count($argv)) {
	$key = array_shift($argv);
	$value = array_shift($argv);
	$opts[$key] = $value;
}

if ($opts['plan'] == 'wordpress_autoinstall'){
	// Setup user
	$username = $opts['user'] . '_usr';
	$dbname = $opts['user'] . '_db';
	$pass = createPassword(8);
	
	// Create the database
	$con = mysql_connect($ip,$username,$password);
	mysql_query("CREATE DATABASE ".$dbname."",$con)or die(mysql_error());
	mysql_query("CREATE USER ".$username."@'' IDENTIFIED BY '".$pass."'",$con) or die(mysql_error());
	mysql_query("GRANT ALL ON ".$dbname.".* to ".$username."@'localhost'",$con) or die(mysql_error());	
	mysql_query("GRANT DROP ON ".$dbname.".* to ".$username."@'localhost'",$con) or die(mysql_error());  	
	
	// Change our working directory
	chdir('/home/'.$opts['user'].'/public_html');
	
	// Remove CGI Bin folder
	shell_exec('rm -rf cgi-bin');
	
	// Download and extract the latest version of Wordpress	
	shell_exec('wget http://wordpress.org/latest.zip');
	shell_exec('unzip latest.zip');
	
	// Extract files, move up a directory, and remove our wordpress folder
	chdir('/home/'.$opts['user'].'/public_html/wordpress');
	shell_exec('mv * ../');
	chdir('/home/'.$opts['user'].'/public_html');
	shell_exec('rm -rf wordpress');
	
	// Create a configuration file based off of the sample
	$content = file_get_contents('wp-config-sample.php');
	
	// Replace the default values in the sample with our custom
	$content = str_replace('database_name_here', $dbname, $content);	
	$content = str_replace('username_here', $username, $content);
	$content = str_replace('password_here', $pass, $content);
	$content = str_replace("'localhost'", "'192.168.1.2'", $content);
	 
	// Create file
	$handle = fopen('wp-config.php', 'x+');
	fwrite($handle, $content);
	fclose($handle);
	
	// Update permissions
	shell_exec('chown -R '.$opts['user'].' *');
	shell_exec('chgrp -R '.$opts['user'].' *');

	// Display our info to the user
	echo 'Wordpress Install...Done<br />';
	echo 'MySQL Pass:'.$pass.'<br />';
}

function createPassword($length) {
	$chars = "234567890abcdefghijkmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
	$i = 0;
	$password = "";
	while ($i <= $length) {
		$password .= $chars{mt_rand(0,strlen($chars))};
		$i++;
	}
	return $password;
}

?>
